CoreBlog.UI/Controllers/BlogController.cs
using AutoMapper;
using CoreBlog.Business.Abstract;
using CoreBlog.Business.DTOs;
using CoreBlog.DataAccess.Context;
using CoreBlog.DataAccess.Extensions;
using CoreBlog.Entity.Concrete;
using CoreBlog.UI.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace CoreBlog.UI.Controllers
{
   
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly ICategoryService _categoryService;
        private readonly IMapper _mapper;
        private readonly IUserClaimHelpers _userClaimHelpers;

        private static List<SelectListItem> Categories;
        public BlogController(IBlogService blogService, ICategoryService categoryService, IMapper mapper, IUserClaimHelpers userClaimHelpers)
        {
            _blogService = blogService;
            _categoryService = categoryService;
            _mapper = mapper;
            Categories = GetCategories().Result;
            _userClaimHelpers = userClaimHelpers;
        }

        public async Task<IActionResult> Index()
        {
            
            var blogs = await _blogService.GetBlogListWithCategory();
            return View(blogs);
        }
        public async Task<IActionResult> BlogDetails(int id)
        {
            var blogs = await _blogService.GetBlogListWithCategory(x => x.BlogID == id);
            return View(blogs.FirstOrDefault());
        }

        public async Task<IActionResult> BlogListByWriter()
        {

            var result = await _blogService.GetBlogListWithCategory(x => x.WriterID == _userClaimHelpers.Id);
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> BlogAdd()
        {
            var categories = await _categoryService.GetListAllAsync();

            BlogDto blogDto = new BlogDto
            {
                Category = Categories ?? await GetCategories()
            };
      


            return View(blogDto);  
        }

        [HttpPost]
        public async Task<IActionResult> BlogAdd(BlogDto blogDto)
        {
            if (!ModelState.IsValid)
            {

                blogDto.Category = Categories ?? await GetCategories();

                return View(blogDto);
            }
            blogDto.BlogStatus = true;
            blogDto.BlogCreatedDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            blogDto.WriterID = _userClaimHelpers.Id;
            
            await _blogService.InsertAsync(_mapper.Map<Blog>(blogDto));
            return RedirectToAction("BlogListByWriter","Blog");
           
        }
        public async Task<IActionResult> BlogDelete(int id)
        {
            var blog = await _blogService.GetByIdAsync(id);
             _blogService.Delete(blog);
            return RedirectToAction("BlogListByWriter", "Blog");
        }

        [HttpGet]
        public async Task<IActionResult> EditBlog(int id)
        {
            var blog =await _blogService.GetByIdAsync(id);
            var blogDto = _mapper.Map<BlogDto>(blog);

            blogDto.Category = Categories ?? await GetCategories();
            return View(blogDto);
        }

        [HttpPost]
        public  IActionResult EditBlog(BlogDto blogDto)
        {
            if (!ModelState.IsValid)
            {
                blogDto.Category = Categories ??  GetCategories().Result;
                return View(blogDto);
            }
            _blogService.Update(_mapper.Map<Blog>(blogDto));
            return RedirectToAction("BlogListByWriter", "Blog");
        }

        public IActionResult Test(BlogDto blogDto)
        {
            if (!ModelState.IsValid)
            {
                blogDto.Category = Categories ?? GetCategories().Result;
                return View(blogDto);
            }
            _blogService.Update(_mapper.Map<Blog>(blogDto));
            return RedirectToAction("BlogListByWriter", "Blog");
        }

        private  async Task<List<SelectListItem>> GetCategories()
        {

            var categories = await _categoryService.GetListAllAsync();

            return categories.Select(x => new SelectListItem
            {
                Text = x.CategoryName,
                Value = x.CategoryID.ToString()
            }).ToList();

        }



        

    }
}

CoreBlog.UI/ViewComponents/Blog/BlogListDasboardViewComponent.cs
using CoreBlog.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CoreBlog.UI.ViewComponents.Blog
{
    public class BlogListDasboardViewComponent:ViewComponent
    {
        private readonly IBlogService _blogService;

        public BlogListDasboardViewComponent(IBlogService blogService)
        {
            _blogService = blogService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var result = await _blogService.GetLastBlogListAsync(10);
            return View(result);
        }
    }
}

CoreBlog.UI/ViewComponents/Blog/FooterLastBlogsViewComponent.cs
using CoreBlog.Business.Abstract;
using CoreBlog.DataAccess.Context;
using CoreBlog.DataAccess.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace CoreBlog.UI.ViewComponents.Blog
{
    
    public class FooterLastBlogsViewComponent:ViewComponent
    {
        private readonly IBlogService _blogService;

        public FooterLastBlogsViewComponent(IBlogService blogService)
        {
            _blogService = blogService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int count)
        {


            var result = await _blogService.GetLastBlogListAsync(3);
            return View(result);
        }
    }
}

CoreBlog.UI/ViewComponents/Blog/WriterLastBlogViewComponent.cs
using CoreBlog.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CoreBlog.UI.ViewComponents.Blog
{
    public class WriterLastBlogViewComponent : ViewComponent
    {
        private readonly IBlogService _blogService;

        public WriterLastBlogViewComponent(IBlogService blogService)
        {
            _blogService = blogService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int writerId)
        {
            var result = await _blogService.GetBlogListWithWriter(x => x.WriterID == writerId);
            return View(result);    
        }
    }
}

CoreBlog.UI/ViewComponents/Category/CategoryListViewComponent.cs
using CoreBlog.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CoreBlog.UI.ViewComponents.Category
{
    public class CategoryListViewComponent:ViewComponent
    {
        private readonly ICategoryService _categoryService;

        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryService.GetCategoryListWithBlog();
            return View(categories);
        }
    }
}

CoreBlog.UI/ViewComponents/Comment/CommentListByBlogViewComponent.cs
using CoreBlog.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CoreBlog.UI.ViewComponents
{
    public class CommentListByBlogViewComponent:ViewComponent
    {
        private readonly ICommentService _commentService;

        public CommentListByBlogViewComponent(ICommentService commentService)
        {
            _commentService = commentService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int id)
        {
            var comments = await _commentService.GetListAllAsync(x => x.BlogID == id);
            return View(comments);
        }
    }
}

CoreBlog.UI/Views/Blog/BlogAdd.cshtml
@model BlogDto

@{
    ViewData["Title"] = "BlogAdd";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h1>Yeni Blog Girişi</h1>

<br />
<div class="row">
    <div class="col-md-12">
        <form asp-action="BlogAdd">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="BlogTitle" class="control-label">Blog Başlığı</label>
                <input asp-for="BlogTitle" class="form-control" />
                <span asp-validation-for="BlogTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogImage" class="control-label">Blog Göreseli</label>
                <input asp-for="BlogImage" class="form-control" />
                <span asp-validation-for="BlogImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogThumbnailImage" class="control-label">Blog Küçük Görseli</label>
                <input asp-for="BlogThumbnailImage" class="form-control" />
                <span asp-validation-for="BlogThumbnailImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="CategoryID" class="control-label">Kategori</label>*@
           
                <select asp-for="CategoryID" asp-items="@Model.Category" class="form-control">
                    <option value="0">Lütfen bir kategori seçiniz</option>
                </select>
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogContent" class="control-label">Blog İçeriği</label>
                <textarea asp-for="BlogContent" class="form-control" rows="15"></textarea>
                <span asp-validation-for="BlogContent" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

CoreBlog.UI/Views/Blog/BlogDetails.cshtml
@model Blog
@{
    ViewData["Title"] = "BlogDetails";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}


<!DOCTYPE html>
<html lang="zxx">


<body>




    <!--//banner-->
    <section class="banner-bottom">
        <!--/blog-->
        <div class="container">
            <div class="row">
                <!--left-->
                <div class="col-lg-8 left-blog-info-w3layouts-agileits text-left">
                    <div class="blog-grid-top">
                        <div class="b-grid-top">
                            <div class="blog_info_left_grid">
                                <a href="single.html">
                                    <img src="~/web/images/b1.jpg" class="img-fluid" alt="">
                                    @*<img src="~/web/images/b1.jpg" />*@
                                </a>
                            </div>
                            <div class="blog-info-middle">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="far fa-calendar-alt"></i>  @(((DateTime) Model.BlogCreatedDate).ToString("dd-MMM-yyyy"))
                                        </a>
                                    </li>
                                    <li class="mx-2">
                                        <a href="#">
                                            <i class="far fa-thumbs-up"></i> 0 Beğeni
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="far fa-comment"></i> 0 Yorum
                                        </a>
                                    </li>

                                </ul>
                            </div>
                        </div>

                        <h3>
                            @*<a href="single.html">@Model.BlogTitle</a>*@
                        </h3>
                        <p>
                            @Model.BlogContent
                        </p>
                        <a href="/Blog/Index/" class="btn btn-primary read-m">Blog Listesi</a>
                    </div>

                    @*@await Html.PartialAsync("~/Views/Comment/CommentListByBlog.cshtml")*@
                    @await Component.InvokeAsync("CommentListByBlog", new { id = Model.BlogID })
                    @await Html.PartialAsync("~/Views/Comment/PartialAddComment.cshtml")

                </div>

                <!--//left-->
                <!--right-->
                <aside class="col-lg-4 agileits-w3ls-right-blog-con text-right">
                    <div class="right-blog-info text-left">
                        <div class="tech-btm">
                            <img src="~/web/images/banner1.jpg" class="img-fluid" alt="">
                        </div>
                        <h4>Mail Bültenine Abone Olun</h4>
                        @await Html.PartialAsync("~/Views/NewsLetter/SubscribeMail.cshtml")
                        @await Component.InvokeAsync("CategoryList")
                        @await Component.InvokeAsync("WriterLastBlog", new { writerId = Model.WriterID })
                        <div class="single-gd my-5 tech-btm">
                            <h4>Our Progress</h4>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 10%" aria-valuenow="10" aria-valuemin="0"
                                     aria-valuemax="100"></div>
                            </div>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0"
                                     aria-valuemax="100"></div>
                            </div>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                     aria-valuemax="100"></div>
                            </div>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped bg-warning" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0"
                                     aria-valuemax="100"></div>
                            </div>
                            <div class="progress">
                                <div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0"
                                     aria-valuemax="100"></div>
                            </div>
                        </div>
                        <div class="single-gd tech-btm">
                            <h4>Son Eklenen Post</h4>
                            <div class="blog-grids">
                                <div class="blog-grid-left">
                                    <a href="single.html">
                                        <img src="~/web/images/b1.jpg" class="img-fluid" alt="">
                                    </a>
                                </div>
                                <div class="blog-grid-right">

                                    <h5>
                                        <a href="single.html">Pellentesque dui, non felis. Maecenas male</a>
                                    </h5>
                                </div>
                                <div class="clearfix"> </div>
                            </div>
                        </div>
                    </div>

                </aside>
                <!--//right-->
            </div>
        </div>
    </section>
    <input type="hidden" id="blogId" value="@Model.BlogID" />
    @section Scripts {
        
        <script>
            $('#btnSubmit').click(function (evt) {
                evt.preventDefault();
                var email = $('#txtMail').val()


                if (email == '') {
                    $('#txtMail').next().show();
                    return false;
                }

                if (IsEmail(email) == false) {
                    alert('formata uygun degıl')
                    $('#txtMail').show();
                    return false;
                }

                console.log(email);
                $.ajax({
                    type: "POST",
                    url: "/NewsLetter/SubscribeMail",
                    data: { "mail": email},
                    success: function (response) {


                        $('#txtMail').val('')
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert(response.responseText);
                    }
                });
            });

           function IsEmail(email) {
               //var regex = /^([\w-\.]+\u0040([\w-]+\.)+[\w-]{2,4})?$/;
               var regex = /^([a-zA-Z0-9_\.\-\+])+\u0040(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
                    if(!regex.test(email)) {
                       return false;
                    }else{
                       return true;
                    }
                  }

        </script>
     
        <script>
            $('#btnAddComment').click(function (e) {
                e.preventDefault();

                var formData = new FormData();

                formData.append("commentUserName", $('#commentUserName').val())
                formData.append("commentTitle", $('#commentTitle').val())
                formData.append("commentContent", $('#commentContent').val())
                formData.append("blogId", $('#blogId').val())
                

                $.ajax({
                    type: "POST",
                    url: "/Comment/PartialAddComment",
                    data: formData,
                  
                    processData: false,
                    contentType: false,
                    success: function (response) {

                        console.log('test');
                        $('#commentUserName').val('')
                        $('#commentTitle').val('')
                        $('#commentContent').val('')

                        swal("Teşekürler!", "Yorumunuz kayıt edildi", "success");
                        
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert('Hata var');
                    }
                });
            })
        </script>
        
    }


</body>

</html>

CoreBlog.UI/Views/Blog/BlogListByWriter.cshtml
@model IEnumerable<Blog>
@{
    ViewData["Title"] = "BlogListByWriter";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Yazarın Blokları</h4>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th> # </th>
                    <th> Blok Başlığı</th>
                    <th> Oluşturma Tarihi </th>
                    <th> Kategori</th>
                    <th> Durum </th>
                    <th> Sil </th>
                    <th> Düzenle</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td> @item.BlogID </td>
                    <td> @item.BlogTitle </td>
                    <td>
                        @item.BlogCreatedDate.ToString("dd-MMM-yyyy")
                    </td>
                    <td> @item.Category.CategoryName </td>
                    @if (item.BlogStatus)
                    {
                        <td>
                            <span class="badge badge-success">Aktif</span>
                        </td>
                    }
                    else
                    {
                        <td>
                            <span class="badge badge-danger">Pasif</span>
                        </td>
                    }



                    <td> <a href="/Blog/BlogDelete/@item.BlogID" class="btn btn-danger">Sil</a> </td>
                    <td> <a href="/Blog/EditBlog/@item.BlogID" class="btn btn-warning">Düzenle</a> </td>
                </tr>
                }

            </tbody>
        </table>


    </div>
    <a href="/Blog/BlogAdd/" class="btn btn-primary">Yeni Blog Oluştur</a>
</div>

CoreBlog.UI/Views/Blog/EditBlog.cshtml
@model BlogDto
@{
    ViewData["Title"] = "EditBlog";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}


<h1>Blog Güncelle</h1>

<br />
<div class="row">
    <div class="col-md-12">
        <form asp-action="EditBlog">
            <input type="hidden" asp-for="BlogID" />
            <input type="hidden" asp-for="WriterID" />
            <input type="hidden" asp-for="BlogCreatedDate" />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="BlogTitle" class="control-label">Blog Başlığı</label>
                <input asp-for="BlogTitle" class="form-control" />
                <span asp-validation-for="BlogTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogImage" class="control-label">Blog Göreseli</label>
                <input asp-for="BlogImage" class="form-control" />
                <span asp-validation-for="BlogImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogThumbnailImage" class="control-label">Blog Küçük Görseli</label>
                <input asp-for="BlogThumbnailImage" class="form-control" />
                <span asp-validation-for="BlogThumbnailImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="CategoryID" class="control-label">Kategori</label>*@

                <select asp-for="CategoryID" asp-items="@Model.Category" class="form-control">
                    <option value="0">Lütfen bir kategori seçiniz</option>
                </select>
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogContent" class="control-label">Blog İçeriği</label>
                <textarea asp-for="BlogContent" class="form-control" rows="15"></textarea>
                <span asp-validation-for="BlogContent" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="BlogStatus" /> Pasif Durumu
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Güncelle" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

CoreBlog.UI/Views/Blog/Index.cshtml
@model List<Blog>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/UserLayout.cshtml";
}

<section class="main-content-w3layouts-agileits">
    <div class="container">
        <h3 class="tittle">Blog Posts</h3>
        <div class="inner-sec">
            <!--left-->
            <div class="left-blog-info-w3layouts-agileits text-left">
                <div class="row">
                    @foreach (var item in Model)
                    {
                        <div class="col-lg-4 card">
                            <a href="~/web/single.html">
                                <img src="@item.BlogImage" class="card-img-top img-fluid" alt="">
                            </a>
                            <div class="card-body">
                                <ul class="blog-icons my-4">
                                    <li>
                                        <a href="~/web/#">
                                            <i class="far fa-calendar-alt"></i> @(((DateTime) item.BlogCreatedDate).ToString("dd-MMM-yyyy"))
                                        </a>
                                    </li>
                                    <li class="mx-2">
                                        <a href="~/web/#">
                                            <i class="far fa-comment"></i> 0
                                        </a>
                                    </li>
                                    <li>
                                        <a href="~/web/#">
                                            <i class="fas fa-eye"></i> 
                                            @item.Category.CategoryName
                                        </a>
                                    </li>

                                </ul>
                                <h5 class="card-title">
                                    <a asp-controller="Blog" asp-action="BlogDetails" asp-route-id="@item.BlogID" >@item.BlogTitle</a>
                                </h5>
                                <p class="card-text mb-3">@item.BlogContent.Substring(0, item.BlogContent.Substring(0,130).LastIndexOf(" "))</p>
                                <a asp-controller="Blog" asp-action="BlogDetails" asp-route-id="@item.BlogID" class="btn btn-primary read-m">Devamını Oku</a>
                            </div>
                        </div>
                    }



                </div>
                <!--//left-->
            </div>
        </div>
    </div>
</section>

CoreBlog.UI/Views/Blog/Test.cshtml
@model CoreBlog.Entity.Concrete.Blog

@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h1>Test</h1>

<h4>Blog</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Test">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BlogID" class="control-label"></label>
                <input asp-for="BlogID" class="form-control" />
                <span asp-validation-for="BlogID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogTitle" class="control-label"></label>
                <input asp-for="BlogTitle" class="form-control" />
                <span asp-validation-for="BlogTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogContent" class="control-label"></label>
                <input asp-for="BlogContent" class="form-control" />
                <span asp-validation-for="BlogContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogThumbnailImage" class="control-label"></label>
                <input asp-for="BlogThumbnailImage" class="form-control" />
                <span asp-validation-for="BlogThumbnailImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogImage" class="control-label"></label>
                <input asp-for="BlogImage" class="form-control" />
                <span asp-validation-for="BlogImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogCreatedDate" class="control-label"></label>
                <input asp-for="BlogCreatedDate" class="form-control" />
                <span asp-validation-for="BlogCreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="BlogStatus" /> @Html.DisplayNameFor(model => model.BlogStatus)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="CategoryID" class="control-label"></label>
                <input asp-for="CategoryID" class="form-control" />
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WriterID" class="control-label"></label>
                <input asp-for="WriterID" class="form-control" />
                <span asp-validation-for="WriterID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>