CoreBlog.UI/ViewComponents/Blog/FooterLastBlogsViewComponent.cs
using CoreBlog.Business.Abstract;
using CoreBlog.DataAccess.Context;
using CoreBlog.DataAccess.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace CoreBlog.UI.ViewComponents.Blog
{
    
    public class FooterLastBlogsViewComponent:ViewComponent
    {
        private readonly IBlogService _blogService;

        public FooterLastBlogsViewComponent(IBlogService blogService)
        {
            _blogService = blogService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int count)
        {


            var result = await _blogService.GetLastBlogListAsync(3);
            return View(result);
        }
    }
}

CoreBlog.UI/Views/Shared/BlogTemplate/Footer.cshtml
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 footer-grid-agileits-w3ls text-left">
                <h3>Hakkımızda</h3>
                <p>İnternet ortaya çıktığında, kullanıcıların genellikle pasif pozisyonda kaldığı bir mecraydı. İçeriğindeki uçsuz bucaksız bilgi havuzu, sadece okunabilen, bakılabilen, izlenebilen ya da dinlenebilen bir yapıdaydı..</p>
                <div class="read">
                    <a href="/About/Index" class="btn btn-primary read-m">Devamını Oku</a>
                </div>
            </div>
            <div class="col-lg-4 footer-grid-agileits-w3ls text-left">

                <div class="tech-btm">
                    <h3>Son Postlar</h3>
                    
                    @await Component.InvokeAsync("FooterLastBlogs")
                </div>
            </div>
            <!-- subscribe -->
            <div class="col-lg-4 subscribe-main footer-grid-agileits-w3ls text-left">
                <h3>Mail Bültenine Abone Olun</h3>
                @await Html.PartialAsync("~/Views/NewsLetter/SubscribeMail.cshtml")
                <!-- //subscribe -->
            </div>
        </div>
        <!-- footer -->
        <div class="footer-cpy text-center">
            <div class="footer-social">
                <div class="copyrighttop">
                    <ul>
                        <li class="mx-3">
                            <a class="facebook" href="~/web/#">
                                <i class="fab fa-facebook-f"></i>
                                <span>Facebook</span>
                            </a>
                        </li>
                        <li>
                            <a class="facebook" href="~/web/#">
                                <i class="fab fa-twitter"></i>
                                <span>Twitter</span>
                            </a>
                        </li>
                        <li class="mx-3">
                            <a class="facebook" href="~/web/#">
                                <i class="fab fa-google-plus-g"></i>
                                <span>Google+</span>
                            </a>
                        </li>
                        <li>
                            <a class="facebook" href="~/web/#">
                                <i class="fab fa-pinterest-p"></i>
                                <span>Pinterest</span>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
            <div class="w3layouts-agile-copyrightbottom">
                <p>
                    © @DateTime.Now.Year Weblog. All Rights Reserved | Design by
                    <a href="~/web/http://w3layouts.com/">W3layouts</a>
                </p>

            </div>
        </div>

        <!-- //footer -->


    </div>
</footer>

CoreBlog.UI/Views/Shared/BlogTemplate/Header.cshtml
<div class="header_top" id="home">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right mx-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/Blog/Index/">
                        Anasayfa
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/About/Index/">Hakkımızda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Blog/Index/">Bloglar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/Contact/Index/">İletişim</a>
                </li>

            </ul>
            <form action="#" method="post" class="form-inline my-2 my-lg-0 header-search">
                <input class="form-control mr-sm-2" type="search" placeholder="Aranacak Kelime..." name="Search" required="">
                <button class="btn btn1 my-2 my-sm-0" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </form>



        </div>
    </nav>
 
</div>

CoreBlog.UI/Views/Shared/BlogTemplate/TopForms.cshtml
<div class="col-md-4 top-forms text-center mt-lg-3 mt-md-1 mt-0">
    <span>Hoşgeldin</span>
    <span class="mx-lg-4 mx-md-2  mx-1">
        <a href="/Login/Index">
            <i class="fas fa-lock"></i> Giriş Yap
        </a>
    </span>
    <span>
        <a href="/Register/Index">
            <i class="far fa-user"></i> Kayıt Ol
        </a>
    </span>
</div>