CoreBlog.UI/Controllers/DashboardController.cs
using CoreBlog.Business.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace CoreBlog.UI.Controllers
{

    public class DashboardController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly ICategoryService _categoryService;

        public DashboardController(IBlogService blogService, ICategoryService categoryService)
        {
            _blogService = blogService;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var blogs = await _blogService.GetListAllAsync();
            ViewBag.TotalBlogCount = blogs.Count();
            ViewBag.TotalWriterByIdCount = blogs.Where(x => x.WriterID == 2).Count();
            ViewBag.TotalCategoryCount = _categoryService.GetListAllAsync().Result.Count();
            return View();
        }
    }
}

CoreBlog.UI/ViewComponents/Blog/BlogListDasboardViewComponent.cs
using CoreBlog.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CoreBlog.UI.ViewComponents.Blog
{
    public class BlogListDasboardViewComponent:ViewComponent
    {
        private readonly IBlogService _blogService;

        public BlogListDasboardViewComponent(IBlogService blogService)
        {
            _blogService = blogService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var result = await _blogService.GetLastBlogListAsync(10);
            return View(result);
        }
    }
}

CoreBlog.UI/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html lang="tr">

<body>


    <div class="page-header">
        <h3 class="page-title">
            <span class="page-title-icon bg-gradient-primary text-white mr-2">
                <i class="mdi mdi-home"></i>
            </span> Dashboard
        </h3>
        
    </div>
    <div class="row">
        <div class="col-md-4 stretch-card grid-margin">
            <div class="card bg-gradient-danger card-img-holder text-white">
                <div class="card-body">
                    <img src="~/writer/assets/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                    <h4 class="font-weight-normal mb-3">
                        Toplam Blog Sayısı <i class="mdi mdi-chart-line mdi-24px float-right"></i>
                    </h4>
                    <h2 class="mb-5">@ViewBag.TotalBlogCount</h2>
                    <h6 class="card-text">MVC 5.0 Proje Kampı</h6>
                </div>
            </div>
        </div>
        <div class="col-md-4 stretch-card grid-margin">
            <div class="card bg-gradient-info card-img-holder text-white">
                <div class="card-body">
                    <img src="~/writer/assets/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                    <h4 class="font-weight-normal mb-3">
                        Sizin Blog Sayınız <i class="mdi mdi-bookmark-outline mdi-24px float-right"></i>
                    </h4>
                    <h2 class="mb-5">@ViewBag.TotalWriterByIdCount</h2>
                    <h6 class="card-text">MVC 5.0 Proje Kampı</h6>
                </div>
            </div>
        </div>
        <div class="col-md-4 stretch-card grid-margin">
            <div class="card bg-gradient-success card-img-holder text-white">
                <div class="card-body">
                    <img src="~/writer/assets/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                    <h4 class="font-weight-normal mb-3">
                        Toplam Kategori Sayısı <i class="mdi mdi-diamond mdi-24px float-right"></i>
                    </h4>
                    <h2 class="mb-5">@ViewBag.TotalCategoryCount</h2>
                    <h6 class="card-text">MVC 5.0 Proje Kampı</h6>
                </div>
            </div>
        </div>
    </div>
    <div class="row">


    </div>
    @await Component.InvokeAsync("BlogListDasboard")

    @await Component.InvokeAsync("WriterAboutOnDashboard",new {id = 2})

    @await Component.InvokeAsync("CategoryListDashboard")


</body>
</html>